fetch("https://exam.global-exam.com/training/activity/start", {
  headers: {
    accept: "text/html, application/xhtml+xml",
    "accept-language": "en-US,en;q=0.9",
    "cache-control": "no-cache",
    "content-type": "application/json;charset=UTF-8",
    pragma: "no-cache",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "sec-gpc": "1",
    "x-csrf-token-prod": "08cmTa2hTWvkeNYkrMKJ8X9BxsCiOpVw6KlVr7SV",
    "x-inertia": "true",
    "x-inertia-version": "4b50dde26bcccfbfe7c7eb6143de2689",
    "x-requested-with": "XMLHttpRequest",
  },
  referrer: "https://exam.global-exam.com/user-plannings/445602",
  referrerPolicy: "strict-origin-when-cross-origin",
  body: '{"userPlanningActivityId":20475962,"activityId":5693}',
  method: "POST",
  mode: "cors",
  credentials: "include",
})
